DROP TABLE IF EXISTS mvp_meetings;
CREATE TABLE mvp_meetings (
    meeting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meeting_name text NOT NULL,
    meeting_type text NOT NULL,
    description text NOT NULL,
    meeting_time text NOT NULL
);