DROP TABLE IF EXISTS meetings;
CREATE TABLE meetings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    _id UUID NOT NULL,
    meeting_name text NOT NULL,
    meeting_type text NOT NULL,
    description text NOT NULL,
    meeting_time TIMESTAMPTZ NOT NULL
);

SET timezone = 'America/New_York';