DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    team_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    _id UUID NOT NULL,
    teams_name text NOT NULL,
    active boolean NOT NULL,
    UNIQUE (teams_name)
);