DROP TABLE IF EXISTS recurring_meetings;
CREATE TABLE recurring_meetings (
    recurring_meeting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recurring_meeting_name text NOT NULL,
    UNIQUE (recurring_meeting_name)
);