DROP TABLE IF EXISTS meetings;
CREATE TABLE meetings (
    meeting_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    _id UUID NOT NULL,
    meeting_name text NOT NULL,
    meeting_type text NOT NULL,
    description text NOT NULL,
    user_team_id int REFERENCES user_team (user_team_pkey) ON DELETE CASCADE,
    recurring boolean NOT NULL,
    recurring_id int REFERENCES recurring_meetings (recurring_meeting_id) ON DELETE CASCADE,
    meeting_time TIMESTAMPTZ NOT NULL
);

SET timezone = 'America/New_York';